export const MAX_VOCABULARY_EXAMPLES = 3;
export const MAX_VOCABULARY_WORD_LENGTH = 80;
export const MAX_VOCABULARY_MEANING_LENGTH = 160;
export const MAX_VOCABULARY_EXAMPLE_LENGTH = 300;
export const MAX_VOCABULARY_DESCRIPTION_LENGTH = 1000;
